/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LawyerId = IDL.Principal;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'fee' : IDL.Nat,
  'status' : BookingStatus,
  'duration' : IDL.Nat,
  'clientId' : IDL.Principal,
  'bookingId' : IDL.Nat,
  'slot' : Time,
  'lawyerId' : LawyerId,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'lawyer' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LawyerStatus = IDL.Variant({
  'pro' : IDL.Null,
  'basic' : IDL.Null,
});
export const Review = IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat });
export const LawyerProfile = IDL.Record({
  'id' : LawyerId,
  'bio' : IDL.Text,
  'fee' : IDL.Nat,
  'consultationsOffered' : IDL.Nat,
  'status' : LawyerStatus,
  'reviews' : IDL.Vec(Review),
  'areasOfExpertise' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'credentials' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(UserRole),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([LawyerId, IDL.Nat, IDL.Text], [], []),
  'adminDeleteBooking' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteLawyerProfile' : IDL.Func([LawyerId], [], []),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'adminGetAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bookConsultation' : IDL.Func(
      [LawyerId, Time, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'bookingId' : IDL.Nat })],
      [],
    ),
  'completeOnboarding' : IDL.Func([UserRole], [], []),
  'createLawyerProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'findLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClientDashboard' : IDL.Func(
      [],
      [IDL.Vec(Booking), IDL.Vec(LawyerProfile)],
      ['query'],
    ),
  'getLawyerDashboard' : IDL.Func(
      [LawyerId],
      [
        LawyerProfile,
        IDL.Vec(Booking),
        IDL.Record({ 'pending' : IDL.Nat, 'confirmed' : IDL.Nat }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateLawyerProfile' : IDL.Func(
      [
        LawyerId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LawyerId = IDL.Principal;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'fee' : IDL.Nat,
    'status' : BookingStatus,
    'duration' : IDL.Nat,
    'clientId' : IDL.Principal,
    'bookingId' : IDL.Nat,
    'slot' : Time,
    'lawyerId' : LawyerId,
  });
  const UserRole = IDL.Variant({ 'client' : IDL.Null, 'lawyer' : IDL.Null });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LawyerStatus = IDL.Variant({ 'pro' : IDL.Null, 'basic' : IDL.Null });
  const Review = IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat });
  const LawyerProfile = IDL.Record({
    'id' : LawyerId,
    'bio' : IDL.Text,
    'fee' : IDL.Nat,
    'consultationsOffered' : IDL.Nat,
    'status' : LawyerStatus,
    'reviews' : IDL.Vec(Review),
    'areasOfExpertise' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'credentials' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(UserRole),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([LawyerId, IDL.Nat, IDL.Text], [], []),
    'adminDeleteBooking' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteLawyerProfile' : IDL.Func([LawyerId], [], []),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'adminGetAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bookConsultation' : IDL.Func(
        [LawyerId, Time, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'bookingId' : IDL.Nat })],
        [],
      ),
    'completeOnboarding' : IDL.Func([UserRole], [], []),
    'createLawyerProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'findLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClientDashboard' : IDL.Func(
        [],
        [IDL.Vec(Booking), IDL.Vec(LawyerProfile)],
        ['query'],
      ),
    'getLawyerDashboard' : IDL.Func(
        [LawyerId],
        [
          LawyerProfile,
          IDL.Vec(Booking),
          IDL.Record({ 'pending' : IDL.Nat, 'confirmed' : IDL.Nat }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateLawyerProfile' : IDL.Func(
        [
          LawyerId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };