/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'fee' : bigint,
  'status' : BookingStatus,
  'duration' : bigint,
  'clientId' : Principal,
  'bookingId' : bigint,
  'slot' : Time,
  'lawyerId' : LawyerId,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type LawyerId = Principal;
export interface LawyerProfile {
  'id' : LawyerId,
  'bio' : string,
  'fee' : bigint,
  'consultationsOffered' : bigint,
  'status' : LawyerStatus,
  'reviews' : Array<Review>,
  'areasOfExpertise' : Array<string>,
  'name' : string,
  'languages' : Array<string>,
  'credentials' : Array<string>,
}
export type LawyerStatus = { 'pro' : null } |
  { 'basic' : null };
export interface Review { 'comment' : string, 'rating' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : [] | [UserRole] }
export type UserRole = { 'client' : null } |
  { 'lawyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[LawyerId, bigint, string], undefined>,
  'adminDeleteBooking' : ActorMethod<[bigint], undefined>,
  'adminDeleteLawyerProfile' : ActorMethod<[LawyerId], undefined>,
  'adminGetAllBookings' : ActorMethod<[], Array<Booking>>,
  'adminGetAllUsers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bookConsultation' : ActorMethod<
    [LawyerId, Time, bigint, bigint],
    { 'bookingId' : bigint }
  >,
  'completeOnboarding' : ActorMethod<[UserRole], undefined>,
  'createLawyerProfile' : ActorMethod<
    [string, string, Array<string>, Array<string>, Array<string>, bigint],
    undefined
  >,
  'findLawyers' : ActorMethod<[], Array<LawyerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClientDashboard' : ActorMethod<
    [],
    [Array<Booking>, Array<LawyerProfile>]
  >,
  'getLawyerDashboard' : ActorMethod<
    [LawyerId],
    [
      LawyerProfile,
      Array<Booking>,
      { 'pending' : bigint, 'confirmed' : bigint },
    ]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateLawyerProfile' : ActorMethod<
    [
      LawyerId,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];